import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { KanjiItem, Level, Manifest, ManifestEntry, Pack, Source, VocabItem } from '@hikkoshi/schemas'
import { SCHEMA_VERSION } from '@hikkoshi/schemas'
import { LEVELS_IN_ORDER } from './config'
import { PACKS_DIR } from './lib/paths'
import { sha256 } from './lib/io'

const PACK_VERSION = '0.1.0'

/** One source record as recorded in content/sources.lock.json. */
export interface LockSource {
  key: string
  name: string
  url: string
  retrieved: string
  license: string
  attribution: string
}

const LEVEL_JLPT: Record<Level, string> = {
  L0: 'kana/survival',
  L1: '≈N5',
  L2: '≈N4',
  L3: '≈N3',
  L4: '≈N2',
  L5: '≈N1',
}

function toSource(s: LockSource): Source {
  return { name: s.name, url: s.url, retrieved: s.retrieved, license: s.license }
}

function buildPack(
  domain: 'vocab' | 'kanji',
  level: Level,
  items: (VocabItem | KanjiItem)[],
  lock: LockSource[],
  date: string,
): Pack {
  const isVocab = domain === 'vocab'
  const dataKeys = isVocab
    ? ['jmdict', 'jlpt-vocab-n5', 'jlpt-vocab-n4', 'jlpt-vocab-n3', 'jlpt-vocab-n2', 'jlpt-vocab-n1']
    : ['kanjidic2', 'kanji-data']
  const sources = lock.filter((s) => dataKeys.includes(s.key)).map(toSource)
  return {
    schemaVersion: SCHEMA_VERSION,
    packId: `${domain}.${level.toLowerCase()}.core`,
    packVersion: PACK_VERSION,
    title: `${isVocab ? 'Vocabulary' : 'Kanji'} — ${level} (${LEVEL_JLPT[level]})`,
    license: {
      spdx: 'CC-BY-SA-4.0',
      notes: `${isVocab ? 'JMdict' : 'KANJIDIC2'} data is CC BY-SA 4.0; JLPT level tags are community estimates (CC BY, Jonathan Waller).`,
    },
    sources,
    levelTagSource: isVocab
      ? 'Jonathan Waller / tanos.co.uk via elzup/jlpt-word-list'
      : 'Jonathan Waller / tanos.co.uk via davidluzgouveia/kanji-data (jlpt_new)',
    levelTagLicense: 'CC-BY',
    verification: {
      status: 'dataset-verified',
      method: isVocab
        ? 'JMdict expression+reading join (unmatched → review-queue.json)'
        : 'KANJIDIC2 literal join',
      date,
    },
    items,
  }
}

function attribution(lock: LockSource[]): string {
  const lines = [
    '# Attribution',
    '',
    'This file is generated by the content pipeline (`pipeline/src/emit.ts`). All language',
    'data in Hikkoshi is imported from licensed open datasets; the app ships no generated',
    'language content (decision D-002). JLPT level tags are community estimates — the JLPT has',
    'published no official vocabulary or kanji lists since 2010 (decision D-005).',
    '',
    '## Datasets',
    '',
  ]
  for (const s of lock) {
    lines.push(`### ${s.name}`, '', `- License: ${s.license}`, `- Source: ${s.url}`, `- ${s.attribution}`, '')
  }
  lines.push(
    '## Required notices',
    '',
    '- **JMdict / KANJIDIC2**: © James William Breen and The Electronic Dictionary Research',
    '  and Development Group. Used under CC BY-SA 4.0 (https://www.edrdg.org/edrdg/licence.html).',
    '- **JLPT level tags**: derived from Jonathan Waller’s JLPT Resources (https://www.tanos.co.uk/jlpt/),',
    '  CC BY. Level tags are estimates, not official.',
    '',
  )
  return lines.join('\n')
}

/** Emit per-level vocab & kanji packs, the manifest, and ATTRIBUTION.md. */
export async function emitPacks(
  vocab: VocabItem[],
  kanji: KanjiItem[],
  lock: LockSource[],
  date: string,
): Promise<Manifest> {
  const entries: ManifestEntry[] = []
  const domains: { domain: 'vocab' | 'kanji'; all: (VocabItem | KanjiItem)[] }[] = [
    { domain: 'vocab', all: vocab },
    { domain: 'kanji', all: kanji },
  ]

  for (const level of LEVELS_IN_ORDER) {
    await mkdir(join(PACKS_DIR, level.toLowerCase()), { recursive: true })
    for (const { domain, all } of domains) {
      const items = all.filter((it) => it.level === level)
      if (items.length === 0) continue
      const pack = buildPack(domain, level, items, lock, date)
      const body = JSON.stringify(pack) + '\n'
      const relPath = `${level.toLowerCase()}/${domain}.json`
      await writeFile(join(PACKS_DIR, relPath), body)
      entries.push({
        packId: pack.packId,
        path: relPath,
        level,
        domain,
        packVersion: PACK_VERSION,
        itemCount: items.length,
        sha256: sha256(Buffer.from(body)), // hash of the exact file bytes
      })
    }
  }

  const manifest: Manifest = { schemaVersion: SCHEMA_VERSION, generatedAt: date, packs: entries }
  await writeFile(join(PACKS_DIR, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n')
  await writeFile(join(PACKS_DIR, '..', 'ATTRIBUTION.md'), attribution(lock))
  return manifest
}
